name: JUNIT Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build all artifacts
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
