name: JUNIT Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Run project gradle
        run: ./gradlew testDebugUnitTest

      - name: HTML Preview
        uses: pavi2410/html-preview-action@v2
        with:
          # The HTML file you want to preview, relative to the root of the repo
          html_file: file:///home/runner/work/2023Voltage/2023Voltage/TeamCode/build/reports/tests/testDebugUnitTest/index.html
